### ISSUE TITLE
hata

### ISSUE THREAD

**Issue by Killers-Hack-Team** [pcdunyasitv/XSSPWN#3]
hocam merhaba ben şöyle bir hata alıyorum hem pipden hemde install.py den yükledim herşeyi 

Traceback (most recent call last):
  File "xsspwn.py", line 7, in <module>
    from ansi.colour import fg,bg 
ImportError: No module named ansi.colour

**Comment by surmelio** [comment]
Merhaba, bende de aynı problem var. Programı çalıştıramıyorum.

Traceback (most recent call last):
  File "xsspwn.py", line 7, in <module>
    from ansi.colour import fg,bg 
ImportError: No module named ansi.colour

**Comment by idrisolcay** [comment]
Bende aynı sorunu yaşadım 

Traceback (most recent call last):
  File "xsspwn.py", line 7, in <module>
    from ansi.colour import fg,bg 
ImportError: No module named ansi.colour

**Comment by pcdunyasitv** [comment]
https://www.youtube.com/watch?v=Tar9H8ZtdfM   bunu izle

hermes2365 ***@***.***>, 6 Eyl 2021 Pzt, 08:53 tarihinde şunu
yazdı:
